### ISSUE TITLE
is this still maintained?

### ISSUE THREAD

**Issue by klauss194** [blikblum/slick-router#87]
Hi,

I'm loving the project - I'm struggling to find a good router for WC. 

Is this still maintained?

**Comment by blikblum** [comment]
Yes. Next release will be easier to configure for web components. Also a lot smaller.

Code wise is done. I need to reorganize how is exposed.

Feel free to ask.

**Comment by blikblum** [comment]
Just released v3.0.0 with many improvements https://github.com/blikblum/slick-router/releases/tag/v3.0.0

I will be adding proper documentation soon
